version: '3'

services:
    etcd-1:
        image: quay.io/coreos/etcd:v3.4.0
        container_name: ff_etcd1
        entrypoint: /usr/local/bin/etcd
        command:
        - '--name=etcd-1'
        - '--initial-advertise-peer-urls=http://etcd-1:2380'
        - '--listen-peer-urls=http://etcd-1:2380'
        - '--listen-client-urls=http://etcd-1:2379,http://localhost:2379'
        - '--advertise-client-urls=http://etcd-1:2379'
        - '--initial-cluster-token=mys3cr3ttok3n'
        - '--heartbeat-interval=250'
        - '--election-timeout=1250'
        - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
        - '--initial-cluster-state=new'
        ports:
        - "2379:2379"

    etcd-2:
        image: quay.io/coreos/etcd:v3.4.0
        container_name: ff_etcd2 
        entrypoint: /usr/local/bin/etcd
        command:
        - '--name=etcd-2'
        - '--initial-advertise-peer-urls=http://etcd-2:2380'
        - '--listen-peer-urls=http://etcd-2:2380'
        - '--listen-client-urls=http://etcd-2:2379,http://localhost:2379'
        - '--advertise-client-urls=http://etcd-2:2379'
        - '--initial-cluster-token=mys3cr3ttok3n'
        - '--heartbeat-interval=250'
        - '--election-timeout=1250'
        - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
        - '--initial-cluster-state=new'
        ports:
        - "3379:2379"

    etcd-3:
        image: quay.io/coreos/etcd:v3.4.0
        container_name: ff_etcd3 
        entrypoint: /usr/local/bin/etcd
        command:
        - '--name=etcd-3'
        - '--initial-advertise-peer-urls=http://etcd-3:2380'
        - '--listen-peer-urls=http://etcd-3:2380'
        - '--listen-client-urls=http://etcd-3:2379,http://localhost:2379'
        - '--advertise-client-urls=http://etcd-3:2379'
        - '--initial-cluster-token=mys3cr3ttok3n'
        - '--heartbeat-interval=250'
        - '--election-timeout=1250'
        - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
        - '--initial-cluster-state=new'
        ports:
        - "4379:2379"